mowing/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('record.urls', namespace='record'))
]

record/urls.py
from django.conf.urls import url
from record import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^home/$', views.home, name='home'),
    url(r'^farm/$', views.farm, name='farm'),
    url(r'^trails/$', views.trails, name='trails'),
]

record/models.py
from django.db import models


class Mowing(models.Model):
    location = models.CharField(max_length=50)
    direction = models.CharField(max_length=25, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}: {} on {}'.format(self.location, self.direction, self.date)

record/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from record.models import Mowing

def index(request):
    if request.method == 'POST':
        post_record(request)
        return HttpResponseRedirect('/')
    else:
        records = Mowing.objects.order_by('date').reverse()
        context = {
            'records': records
        }
        return render(request, 'index.html', context)

def post_record(request):
    location = request.POST['location']
    direction = request.POST['direction']
    session = Mowing.objects.create(location=location, direction=direction)
    session.save()

def home(request):
    return render(request, 'home.html')

def farm(request):
    return render(request, 'farm.html')

def trails(request):
    return render(request, 'trails.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Mowing Records</title>
  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
  <link rel="stylesheet" href="{% static "css/main.css" %}">
</head>
<body>
<div class="container">
  {% block body_block %}
  {% endblock %}
</div>
</body>
</html>

templates/farm.html
<!DOCTYPE html>
{% extends "base.html" %}
  {% block body_block %}
    <h1 class="text-center">Farm</h1>
    <div class="row">
      <div class="col-sm-6">
        <form action="/" method='POST' class="submit-form">
          {% csrf_token %}
          <input type="hidden" name="location" value="Farm">
          <input type="hidden" name="direction" value="North/South">
          <input type="submit" class="btn btn-primary btn-lg submit" value="North/South">
        </form>
        </div>
      <div class="col-sm-6">
        <form action="/" method='POST' class="submit-form">
          {% csrf_token %}
          <input type="hidden" name="location" value="Farm">
          <input type="hidden" name="direction" value="East/West">
          <input type="submit" class="btn btn-primary btn-lg submit" value="East/West">
        </form>
      </div>
    </div>
  {% endblock %}

templates/home.html
<!DOCTYPE html>
{% extends "base.html" %}
  {% block body_block %}
    <h1 class="text-center">Home</h1>
    <div class="row">
      <div class="col-sm-6">
        <form action="/" method='POST' class="submit-form">
          {% csrf_token %}
          <input type="hidden" name="location" value="Home">
          <input type="hidden" name="direction" value="North/South">
          <input type="submit" class="btn btn-primary btn-lg submit" value="North/South">
        </form>
        </div>
      <div class="col-sm-6">
        <form action="/" method='POST' class="submit-form">
          {% csrf_token %}
          <input type="hidden" name="location" value="Home">
          <input type="hidden" name="direction" value="East/West">
          <input type="submit" class="btn btn-primary btn-lg submit" value="East/West">
        </form>
      </div>
    </div>
  {% endblock %}

templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
  <h1 class="text-center">Mowing Records</h1>
  <div class="row">
    <div class="col-xs-4">
      <a href="{% url 'record:home' %}" class="btn btn-primary btn-lg post-link text-center">Home</a>
    </div>
    <div class="col-xs-4">
      <a href="{% url 'record:farm' %}" class="btn btn-primary btn-lg post-link text-center">Farm</a>
    </div>
    <div class="col-xs-4">
      <a href="{% url 'record:trails' %}" class="btn btn-primary btn-lg post-link text-center">Trails</a>
    </div>
  </div>
  <table class="table">
    <tr>
      <th>Location</th>
      <th>Direction</th>
      <th>Date</th>
    </tr>
    {% for record in records %}
      <tr>
        <td>{{ record.location }}</td>
        <td>{{ record.direction }}</td>
        <td>{{ record.date|date:'l, M/d' }}</td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

templates/trails.html
<!DOCTYPE html>
{% extends "base.html" %}
  {% block body_block %}
    <h1 class="text-center">Trails</h1>
        <form action="/" method='POST' class="submit-form">
          {% csrf_token %}
          <input type="hidden" name="location" value="Trails">
          <input type="hidden" name="direction" value="">
          <input type="submit" class="btn btn-primary btn-lg submit" value="Trails">
        </form>
    </div>
  {% endblock %}